export interface City {
    value: string;
    label: string;
    state: string;
}

export const US_CITIES: City[] = [
    { value: "New York", label: "New York, NY", state: "NY" },
    { value: "Los Angeles", label: "Los Angeles, CA", state: "CA" },
    { value: "Chicago", label: "Chicago, IL", state: "IL" },
    { value: "Houston", label: "Houston, TX", state: "TX" },
    { value: "Phoenix", label: "Phoenix, AZ", state: "AZ" },
    { value: "Philadelphia", label: "Philadelphia, PA", state: "PA" },
    { value: "San Antonio", label: "San Antonio, TX", state: "TX" },
    { value: "San Diego", label: "San Diego, CA", state: "CA" },
    { value: "Dallas", label: "Dallas, TX", state: "TX" },
    { value: "San Jose", label: "San Jose, CA", state: "CA" },
    { value: "Austin", label: "Austin, TX", state: "TX" },
    { value: "Jacksonville", label: "Jacksonville, FL", state: "FL" },
    { value: "Fort Worth", label: "Fort Worth, TX", state: "TX" },
    { value: "Columbus", label: "Columbus, OH", state: "OH" },
    { value: "Indianapolis", label: "Indianapolis, IN", state: "IN" },
    { value: "Charlotte", label: "Charlotte, NC", state: "NC" },
    { value: "San Francisco", label: "San Francisco, CA", state: "CA" },
    { value: "Seattle", label: "Seattle, WA", state: "WA" },
    { value: "Denver", label: "Denver, CO", state: "CO" },
    { value: "Washington", label: "Washington, DC", state: "DC" },
    { value: "Nashville", label: "Nashville, TN", state: "TN" },
    { value: "Oklahoma City", label: "Oklahoma City, OK", state: "OK" },
    { value: "El Paso", label: "El Paso, TX", state: "TX" },
    { value: "Boston", label: "Boston, MA", state: "MA" },
    { value: "Portland", label: "Portland, OR", state: "OR" },
    { value: "Las Vegas", label: "Las Vegas, NV", state: "NV" },
    { value: "Detroit", label: "Detroit, MI", state: "MI" },
    { value: "Memphis", label: "Memphis, TN", state: "TN" },
    { value: "Louisville", label: "Louisville, KY", state: "KY" },
    { value: "Baltimore", label: "Baltimore, MD", state: "MD" },
    { value: "Milwaukee", label: "Milwaukee, WI", state: "WI" },
    { value: "Albuquerque", label: "Albuquerque, NM", state: "NM" },
    { value: "Tucson", label: "Tucson, AZ", state: "AZ" },
    { value: "Fresno", label: "Fresno, CA", state: "CA" },
    { value: "Sacramento", label: "Sacramento, CA", state: "CA" },
    { value: "Mesa", label: "Mesa, AZ", state: "AZ" },
    { value: "Kansas City", label: "Kansas City, MO", state: "MO" },
    { value: "Atlanta", label: "Atlanta, GA", state: "GA" },
    { value: "Colorado Springs", label: "Colorado Springs, CO", state: "CO" },
    { value: "Omaha", label: "Omaha, NE", state: "NE" },
    { value: "Raleigh", label: "Raleigh, NC", state: "NC" },
    { value: "Virginia Beach", label: "Virginia Beach, VA", state: "VA" },
    { value: "Miami", label: "Miami, FL", state: "FL" },
    { value: "Oakland", label: "Oakland, CA", state: "CA" },
    { value: "Minneapolis", label: "Minneapolis, MN", state: "MN" },
    { value: "Tulsa", label: "Tulsa, OK", state: "OK" },
    { value: "Bakersfield", label: "Bakersfield, CA", state: "CA" },
    { value: "Wichita", label: "Wichita, KS", state: "KS" },
    { value: "Arlington", label: "Arlington, TX", state: "TX" },
    { value: "Aurora", label: "Aurora, CO", state: "CO" },
    { value: "Tampa", label: "Tampa, FL", state: "FL" },
    { value: "New Orleans", label: "New Orleans, LA", state: "LA" },
    { value: "Cleveland", label: "Cleveland, OH", state: "OH" },
    { value: "Honolulu", label: "Honolulu, HI", state: "HI" },
    { value: "Anaheim", label: "Anaheim, CA", state: "CA" },
    { value: "Lexington", label: "Lexington, KY", state: "KY" },
    { value: "Stockton", label: "Stockton, CA", state: "CA" },
    { value: "Corpus Christi", label: "Corpus Christi, TX", state: "TX" },
    { value: "Henderson", label: "Henderson, NV", state: "NV" },
    { value: "Riverside", label: "Riverside, CA", state: "CA" },
    { value: "Newark", label: "Newark, NJ", state: "NJ" },
    { value: "Saint Paul", label: "Saint Paul, MN", state: "MN" },
    { value: "Santa Ana", label: "Santa Ana, CA", state: "CA" },
    { value: "Cincinnati", label: "Cincinnati, OH", state: "OH" },
    { value: "Irvine", label: "Irvine, CA", state: "CA" },
    { value: "Orlando", label: "Orlando, FL", state: "FL" },
    { value: "Pittsburgh", label: "Pittsburgh, PA", state: "PA" },
    { value: "St. Louis", label: "St. Louis, MO", state: "MO" },
    { value: "Greensboro", label: "Greensboro, NC", state: "NC" },
    { value: "Jersey City", label: "Jersey City, NJ", state: "NJ" },
    { value: "Anchorage", label: "Anchorage, AK", state: "AK" },
    { value: "Lincoln", label: "Lincoln, NE", state: "NE" },
    { value: "Plano", label: "Plano, TX", state: "TX" },
    { value: "Durham", label: "Durham, NC", state: "NC" },
    { value: "Buffalo", label: "Buffalo, NY", state: "NY" },
    { value: "Chandler", label: "Chandler, AZ", state: "AZ" },
    { value: "Chula Vista", label: "Chula Vista, CA", state: "CA" },
    { value: "Toledo", label: "Toledo, OH", state: "OH" },
    { value: "Madison", label: "Madison, WI", state: "WI" },
    { value: "Gilbert", label: "Gilbert, AZ", state: "AZ" },
    { value: "Reno", label: "Reno, NV", state: "NV" },
    { value: "Fort Wayne", label: "Fort Wayne, IN", state: "IN" },
    { value: "North Las Vegas", label: "North Las Vegas, NV", state: "NV" },
    { value: "St. Petersburg", label: "St. Petersburg, FL", state: "FL" },
    { value: "Lubbock", label: "Lubbock, TX", state: "TX" },
    { value: "Irving", label: "Irving, TX", state: "TX" },
    { value: "Laredo", label: "Laredo, TX", state: "TX" },
    { value: "Winston-Salem", label: "Winston-Salem, NC", state: "NC" },
    { value: "Chesapeake", label: "Chesapeake, VA", state: "VA" },
    { value: "Glendale", label: "Glendale, AZ", state: "AZ" },
    { value: "Garland", label: "Garland, TX", state: "TX" },
    { value: "Scottsdale", label: "Scottsdale, AZ", state: "AZ" },
    { value: "Norfolk", label: "Norfolk, VA", state: "VA" },
    { value: "Boise", label: "Boise, ID", state: "ID" },
    { value: "Fremont", label: "Fremont, CA", state: "CA" },
    { value: "Spokane", label: "Spokane, WA", state: "WA" },
    { value: "Santa Clarita", label: "Santa Clarita, CA", state: "CA" },
    { value: "Baton Rouge", label: "Baton Rouge, LA", state: "LA" },
    { value: "Richmond", label: "Richmond, VA", state: "VA" },
    { value: "Hialeah", label: "Hialeah, FL", state: "FL" },
    { value: "San Bernardino", label: "San Bernardino, CA", state: "CA" },
    { value: "Tacoma", label: "Tacoma, WA", state: "WA" },
    { value: "Modesto", label: "Modesto, CA", state: "CA" },
    { value: "Huntsville", label: "Huntsville, AL", state: "AL" },
    { value: "Des Moines", label: "Des Moines, IA", state: "IA" },
    { value: "Yonkers", label: "Yonkers, NY", state: "NY" },
    { value: "Rochester", label: "Rochester, NY", state: "NY" },
    { value: "Moreno Valley", label: "Moreno Valley, CA", state: "CA" },
    { value: "Fayetteville", label: "Fayetteville, NC", state: "NC" },
    { value: "Fontana", label: "Fontana, CA", state: "CA" },
    { value: "Columbus", label: "Columbus, GA", state: "GA" },
    { value: "Worcester", label: "Worcester, MA", state: "MA" },
    { value: "Port St. Lucie", label: "Port St. Lucie, FL", state: "FL" },
    { value: "Little Rock", label: "Little Rock, AR", state: "AR" },
    { value: "Augusta", label: "Augusta, GA", state: "GA" },
    { value: "Oxnard", label: "Oxnard, CA", state: "CA" },
    { value: "Birmingham", label: "Birmingham, AL", state: "AL" },
    { value: "Montgomery", label: "Montgomery, AL", state: "AL" },
    { value: "Frisco", label: "Frisco, TX", state: "TX" },
    { value: "Amarillo", label: "Amarillo, TX", state: "TX" },
    { value: "Salt Lake City", label: "Salt Lake City, UT", state: "UT" },
    { value: "Grand Rapids", label: "Grand Rapids, MI", state: "MI" },
    { value: "Huntington Beach", label: "Huntington Beach, CA", state: "CA" },
    { value: "Overland Park", label: "Overland Park, KS", state: "KS" },
    { value: "Glendale", label: "Glendale, CA", state: "CA" },
    { value: "Tallahassee", label: "Tallahassee, FL", state: "FL" },
    { value: "Grand Prairie", label: "Grand Prairie, TX", state: "TX" },
    { value: "McKinney", label: "McKinney, TX", state: "TX" },
    { value: "Cape Coral", label: "Cape Coral, FL", state: "FL" },
    { value: "Sioux Falls", label: "Sioux Falls, SD", state: "SD" },
    { value: "Peoria", label: "Peoria, AZ", state: "AZ" },
    { value: "Providence", label: "Providence, RI", state: "RI" },
    { value: "Vancouver", label: "Vancouver, WA", state: "WA" },
    { value: "Knoxville", label: "Knoxville, TN", state: "TN" },
    { value: "Akron", label: "Akron, OH", state: "OH" },
    { value: "Mobile", label: "Mobile, AL", state: "AL" },
    { value: "Brownsville", label: "Brownsville, TX", state: "TX" },
    { value: "Newport News", label: "Newport News, VA", state: "VA" },
    { value: "Fort Lauderdale", label: "Fort Lauderdale, FL", state: "FL" },
    { value: "Chattanooga", label: "Chattanooga, TN", state: "TN" },
    { value: "Tempe", label: "Tempe, AZ", state: "AZ" },
    { value: "Aurora", label: "Aurora, IL", state: "IL" },
    { value: "Santa Rosa", label: "Santa Rosa, CA", state: "CA" },
    { value: "Eugene", label: "Eugene, OR", state: "OR" },
    { value: "Elk Grove", label: "Elk Grove, CA", state: "CA" },
    { value: "Salem", label: "Salem, OR", state: "OR" },
    { value: "Ontario", label: "Ontario, CA", state: "CA" },
    { value: "Lancaster", label: "Lancaster, CA", state: "CA" },
    { value: "Killeen", label: "Killeen, TX", state: "TX" },
    { value: "Surprise", label: "Surprise, AZ", state: "AZ" },
    { value: "Garden Grove", label: "Garden Grove, CA", state: "CA" },
    { value: "Pembroke Pines", label: "Pembroke Pines, FL", state: "FL" },
    { value: "Fort Collins", label: "Fort Collins, CO", state: "CO" },
    { value: "Corona", label: "Corona, CA", state: "CA" },
    { value: "Springfield", label: "Springfield, MO", state: "MO" },
    { value: "Jackson", label: "Jackson, MS", state: "MS" },
    { value: "Marietta", label: "Marietta, GA", state: "GA" },
    { value: "Cary", label: "Cary, NC", state: "NC" },
    { value: "Palmdale", label: "Palmdale, CA", state: "CA" },
    { value: "Hayward", label: "Hayward, CA", state: "CA" },
    { value: "Salinas", label: "Salinas, CA", state: "CA" },
    { value: "Murfreesboro", label: "Murfreesboro, TN", state: "TN" },
    { value: "Pasadena", label: "Pasadena, TX", state: "TX" },
    { value: "Kansas City", label: "Kansas City, KS", state: "KS" },
    { value: "Hollywood", label: "Hollywood, FL", state: "FL" },
    { value: "Pomona", label: "Pomona, CA", state: "CA" },
    { value: "Escondido", label: "Escondido, CA", state: "CA" },
    { value: "Joliet", label: "Joliet, IL", state: "IL" },
    { value: "Clarksville", label: "Clarksville, TN", state: "TN" },
    { value: "Paterson", label: "Paterson, NJ", state: "NJ" },
    { value: "Macon", label: "Macon, GA", state: "GA" },
    { value: "Bridgeport", label: "Bridgeport, CT", state: "CT" },
    { value: "Naperville", label: "Naperville, IL", state: "IL" },
    { value: "Savannah", label: "Savannah, GA", state: "GA" },
    { value: "Alexandria", label: "Alexandria, VA", state: "VA" },
    { value: "McAllen", label: "McAllen, TX", state: "TX" },
    { value: "Mesquite", label: "Mesquite, TX", state: "TX" },
    { value: "Syracuse", label: "Syracuse, NY", state: "NY" },
    { value: "Fullerton", label: "Fullerton, CA", state: "CA" },
    { value: "Pasadena", label: "Pasadena, CA", state: "CA" },
    { value: "Bellevue", label: "Bellevue, WA", state: "WA" },
    { value: "Orange", label: "Orange, CA", state: "CA" },
    { value: "Roseville", label: "Roseville, CA", state: "CA" },
    { value: "Denton", label: "Denton, TX", state: "TX" },
    { value: "Waco", label: "Waco, TX", state: "TX" },
    { value: "Surprise", label: "Surprise, AZ", state: "AZ" },
    { value: "Olathe", label: "Olathe, KS", state: "KS" },
    { value: "Thornton", label: "Thornton, CO", state: "CO" },
    { value: "West Valley City", label: "West Valley City, UT", state: "UT" },
    { value: "Dayton", label: "Dayton, OH", state: "OH" },
    { value: "Visalia", label: "Visalia, CA", state: "CA" },
    { value: "Hampton", label: "Hampton, VA", state: "VA" },
    { value: "Gainesville", label: "Gainesville, FL", state: "FL" },
    { value: "Miramar", label: "Miramar, FL", state: "FL" },
    { value: "Warren", label: "Warren, MI", state: "MI" },
    { value: "Coral Springs", label: "Coral Springs, FL", state: "FL" },
    { value: "Cedar Rapids", label: "Cedar Rapids, IA", state: "IA" },
    { value: "Round Rock", label: "Round Rock, TX", state: "TX" },
    { value: "Sterling Heights", label: "Sterling Heights, MI", state: "MI" },
    { value: "Kent", label: "Kent, WA", state: "WA" },
    { value: "Columbia", label: "Columbia, SC", state: "SC" },
    { value: "Santa Clara", label: "Santa Clara, CA", state: "CA" },
    { value: "New Haven", label: "New Haven, CT", state: "CT" },
    { value: "Stamford", label: "Stamford, CT", state: "CT" },
    { value: "Concord", label: "Concord, CA", state: "CA" },
    { value: "Elizabeth", label: "Elizabeth, NJ", state: "NJ" },
    { value: "Lafayette", label: "Lafayette, LA", state: "LA" },
    { value: "Thousand Oaks", label: "Thousand Oaks, CA", state: "CA" },
    { value: "Simi Valley", label: "Simi Valley, CA", state: "CA" },
    { value: "Topeka", label: "Topeka, KS", state: "KS" },
    { value: "Athens", label: "Athens, GA", state: "GA" },
    { value: "Hartford", label: "Hartford, CT", state: "CT" },
    { value: "Norman", label: "Norman, OK", state: "OK" },
    { value: "Victorville", label: "Victorville, CA", state: "CA" },
    { value: "Fargo", label: "Fargo, ND", state: "ND" },
    { value: "Berkeley", label: "Berkeley, CA", state: "CA" },
    { value: "Vallejo", label: "Vallejo, CA", state: "CA" },
    { value: "Abilene", label: "Abilene, TX", state: "TX" },
    { value: "Columbia", label: "Columbia, MO", state: "MO" },
    { value: "Ann Arbor", label: "Ann Arbor, MI", state: "MI" },
    { value: "Allentown", label: "Allentown, PA", state: "PA" },
    { value: "Pearland", label: "Pearland, TX", state: "TX" },
    { value: "Beaumont", label: "Beaumont, TX", state: "TX" },
    { value: "Wilmington", label: "Wilmington, NC", state: "NC" },
    { value: "Evansville", label: "Evansville, IN", state: "IN" },
    { value: "Provo", label: "Provo, UT", state: "UT" },
    { value: "Lansing", label: "Lansing, MI", state: "MI" },
    { value: "Odessa", label: "Odessa, TX", state: "TX" },
    { value: "Richardson", label: "Richardson, TX", state: "TX" },
    { value: "Arvada", label: "Arvada, CO", state: "CO" },
    { value: "Independence", label: "Independence, MO", state: "MO" },
    { value: "Fairfield", label: "Fairfield, CA", state: "CA" },
    { value: "Rochester", label: "Rochester, MN", state: "MN" },
    { value: "West Jordan", label: "West Jordan, UT", state: "UT" },
    { value: "Carlsbad", label: "Carlsbad, CA", state: "CA" },
    { value: "Costa Mesa", label: "Costa Mesa, CA", state: "CA" },
    { value: "Miami Gardens", label: "Miami Gardens, FL", state: "FL" },
    { value: "Cambridge", label: "Cambridge, MA", state: "MA" },
    { value: "El Monte", label: "El Monte, CA", state: "CA" },
    { value: "College Station", label: "College Station, TX", state: "TX" },
    { value: "Downey", label: "Downey, CA", state: "CA" },
    { value: "Temecula", label: "Temecula, CA", state: "CA" },
    { value: "Inglewood", label: "Inglewood, CA", state: "CA" },
    { value: "Centennial", label: "Centennial, CO", state: "CO" },
    { value: "Lowell", label: "Lowell, MA", state: "MA" },
    { value: "Clearwater", label: "Clearwater, FL", state: "FL" },
    { value: "Gresham", label: "Gresham, OR", state: "OR" },
    { value: "Antioch", label: "Antioch, CA", state: "CA" },
    { value: "Richmond", label: "Richmond, CA", state: "CA" },
    { value: "West Covina", label: "West Covina, CA", state: "CA" },
    { value: "Pueblo", label: "Pueblo, CO", state: "CO" },
    { value: "Murrieta", label: "Murrieta, CA", state: "CA" },
    { value: "Ventura", label: "Ventura, CA", state: "CA" },
    { value: "High Point", label: "High Point, NC", state: "NC" },
    { value: "Norwalk", label: "Norwalk, CA", state: "CA" },
    { value: "Daly City", label: "Daly City, CA", state: "CA" },
    { value: "Burbank", label: "Burbank, CA", state: "CA" },
    { value: "Everett", label: "Everett, WA", state: "WA" },
    { value: "Palm Bay", label: "Palm Bay, FL", state: "FL" },
    { value: "Wichita Falls", label: "Wichita Falls, TX", state: "TX" },
    { value: "Green Bay", label: "Green Bay, WI", state: "WI" },
    { value: "Broken Arrow", label: "Broken Arrow, OK", state: "OK" },
    { value: "Pompano Beach", label: "Pompano Beach, FL", state: "FL" },
    { value: "North Charleston", label: "North Charleston, SC", state: "SC" },
    { value: "West Palm Beach", label: "West Palm Beach, FL", state: "FL" },
    { value: "Boulder", label: "Boulder, CO", state: "CO" },
    { value: "Rialto", label: "Rialto, CA", state: "CA" },
    { value: "Santa Maria", label: "Santa Maria, CA", state: "CA" },
    { value: "El Cajon", label: "El Cajon, CA", state: "CA" },
    { value: "Davenport", label: "Davenport, IA", state: "IA" },
    { value: "San Mateo", label: "San Mateo, CA", state: "CA" },
    { value: "Edison", label: "Edison, NJ", state: "NJ" },
    { value: "Woodbridge", label: "Woodbridge, NJ", state: "NJ" },
    { value: "South Bend", label: "South Bend, IN", state: "IN" },
    { value: "Lakeland", label: "Lakeland, FL", state: "FL" },
    { value: "Erie", label: "Erie, PA", state: "PA" },
    { value: "Tyler", label: "Tyler, TX", state: "TX" },
    { value: "Jurupa Valley", label: "Jurupa Valley, CA", state: "CA" },
    { value: "Lewisville", label: "Lewisville, TX", state: "TX" },
    { value: "Sandy Springs", label: "Sandy Springs, GA", state: "GA" },
    { value: "Hillsboro", label: "Hillsboro, OR", state: "OR" },
    { value: "Sparks", label: "Sparks, NV", state: "NV" },
    { value: "League City", label: "League City, TX", state: "TX" },
    { value: "San Angelo", label: "San Angelo, TX", state: "TX" }
];
